# Generated by Django 4.1 on 2022-09-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posocion', models.CharField(max_length=100)),
                ('fuerza', models.CharField(max_length=100)),
                ('potencia', models.CharField(max_length=100)),
                ('velocidad', models.CharField(max_length=100)),
            ],
        ),
    ]
