# Generated by Django 4.1 on 2022-09-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_cartas_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartas',
            name='rendimiento_total',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
