# Generated by Django 4.1 on 2022-09-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_cartas_rendimiento_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartas',
            old_name='potencia',
            new_name='tiro',
        ),
    ]
