# Generated by Django 4.1 on 2022-09-06 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0006_cartas_b_cartas_c_cartas_d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartas_a',
            old_name='posocion',
            new_name='posicion',
        ),
    ]
