# Generated by Django 4.1 on 2022-09-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0007_rename_posocion_cartas_a_posicion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartas_B',
        ),
        migrations.DeleteModel(
            name='Cartas_C',
        ),
        migrations.DeleteModel(
            name='Cartas_D',
        ),
    ]
