# Generated by Django 4.1 on 2022-09-07 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juego', '0008_delete_cartas_b_delete_cartas_c_delete_cartas_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='cartas_a',
            name='clasificacion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_jugadores', models.CharField(max_length=100)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.cartas_a')),
                ('juagadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='carta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.cartas_a'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
