# Generated by Django 4.1 on 2022-09-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0009_jugador_cartas_a_clasificacion_partida_jugador_carta_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartas_A',
            new_name='Cartas',
        ),
    ]
